### ISSUE TITLE
signup screen (if - else statement)

### ISSUE THREAD

**Issue by logesixas96** [logesixas96/Web-QR-System#6]
![Screenshot 2022-07-03 121618](https://user-images.githubusercontent.com/108042238/177024372-a3509731-cda5-4c18-a43d-896457b473eb.png)

Do you have any suggestion on what error handling statement should be imposed on `return null;`?

**Comment by kshorenicholas** [comment]
To be honest, we can leave it as null unless we need the statement to return something else. Would leave it as it unless there is a conflict in the application
