### ISSUE TITLE
need to change to avoid BuildContext across async gaps

### ISSUE THREAD

**Issue by kshorenicholas** [logesixas96/Web-QR-System#7]
Description of issue:

> DO NOT use BuildContext across asynchronous gaps.
>
>Storing BuildContext for later usage can easily lead to difficult to diagnose crashes. Asynchronous gaps are implicitly storing BuildContext and are some of the easiest to overlook when writing code.
>
>When a BuildContext is used from a StatefulWidget, the mounted property must be checked after an asynchronous gap.

Relevant documentation: [https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html](url)

https://github.com/logesixas96/Web-QR-System/blob/b3383c1c6fb036ae52c1aeec9015a90320bc55fc/lib/screens/userdashboard.dart#L152-L156

**Comment by kshorenicholas** [comment]
I will work on it ASAP. This issue may cause problems down the line and I would like to prevent avoidable errors

**Comment by kshorenicholas** [comment]
Not sure if it would have a reasonable impact to the application and whether its something we should ignore nor fix. Testing does not show an impact from what i can see at the very least

**Comment by logesixas96** [comment]
I have tested thoroughly so far didn't face any problem with the function.
I guess we just let it be for now.

**Comment by kshorenicholas** [comment]
Another place where it occurs.

https://github.com/logesixas96/Web-QR-System/blob/ab8ae3c5758d3a51845595ce7188b67eb1de5367/lib/screens/qrhistory.dart#L206

**Comment by logesixas96** [comment]
Yes we do need the navigator for the button to return users back to qrhistory.dart screen after pressing confirm delete, else the screen will remain on AlertDialog box. I'll try look for alternative.

**Comment by logesixas96** [comment]
`Future<void> myAsyncMethod(BuildContext context, VoidCallback onSuccess) async {
    await Future.delayed(const Duration(seconds: 2));
    onSuccess.call();
  }`

`if (!mounted) return;`

This fixed the error for both qrhistory.dart and userdashboard.dart screens.

**Comment by kshorenicholas** [comment]
Thank you for the fix. I knew that I had to put `if (!mounted) return;` somewhere but completely flew past my head to put it before calling `Navigator.of(context`.

**Comment by kshorenicholas** [comment]
closing issue for now
